### ISSUE TITLE
Declaring the Hathora version for the project

### ISSUE THREAD

**Issue by kasbah** [hpx7/rtag#171]
I was just trying out https://github.com/hpx7/tussie-mussie and `hathora dev` fails: <details>

```
Project root: /tmp/tussie-mussie
Installing dependencies in /tmp/tussie-mussie/api

added 5 packages, and audited 6 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/client/.hathora

added 14 packages, and audited 15 packages in 6s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/client/prototype-ui
npm WARN deprecated @types/history@5.0.0: This is a stub types definition. history provides its own type definitions, so you do not need this installed.

added 122 packages, and audited 123 packages in 13s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/client/web

up to date, audited 35 packages in 525ms

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/client/prototype-ui/plugins/Card

up to date, audited 14 packages in 501ms

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/server

up to date, audited 2 packages in 468ms

found 0 vulnerabilities
Installing dependencies in /tmp/tussie-mussie/server/.hathora

added 10 packages, and audited 11 packages in 4s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(node:38265) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Connected to coordinator at coordinator.hathora.dev
Starting frontend at /tmp/tussie-mussie/client/prototype-ui
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json.

    ../../../../home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29521:10:
      29521 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29521:11)
    at resolvePackageEntry (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29517:9)
    at tryResolveFile (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29247:38)
    at tryFsResolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29229:16)
    at Context.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29107:28)
    at Object.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38255:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38458:26)
    at async /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38644:34
    at async callback (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:920:28)

  This error came from the "onResolve" callback registered here:

    ../../../../home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38640:18:
      38640 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38640:19)
    at handlePlugins (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:842:23)
    at Object.buildOrServe (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1136:7)
    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:2064:17
    at new Promise (<anonymous>)
    at Object.build (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:2063:14)
    at Object.build (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1913:51)
    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38416:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    ../../client/prototype-ui/State.tsx:7:23:
      7 │ import CardPlugin from "./plugins/Card";
        ╵                        ~~~~~~~~~~~~~~~~

/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1602
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../../../home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29521:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1602:15)
    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1248:28
    at runOnEndCallbacks (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1033:63)
    at buildResponseToResult (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1246:7)
    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1355:14
    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:665:9
    at handleIncomingPacket (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json.
          at packageEntryFailure (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29521:11)
          at resolvePackageEntry (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29517:9)
          at tryResolveFile (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29247:38)
          at tryFsResolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29229:16)
          at Context.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29107:28)
          at Object.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38255:55)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async resolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38458:26)
          at async /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38644:34
          at async callback (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:920:28),
      location: {
        column: 10,
        file: '../../../../home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js',
        length: 0,
        line: 29521,
        lineText: '    throw new Error(`Failed to resolve entry for package "${id}". ` +\n' +
          '    at packageEntryFailure (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29521:11)\n' +
          '    at resolvePackageEntry (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29517:9)\n' +
          '    at tryResolveFile (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29247:38)\n' +
          '    at tryFsResolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29229:16)\n' +
          '    at Context.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:29107:28)\n' +
          '    at Object.resolveId (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38255:55)\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async resolve (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38458:26)\n' +
          '    at async /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38644:34\n' +
          '    at async callback (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:920:28)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 18,
            file: '../../../../home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js',
            length: 9,
            line: 38640,
            lineText: '            build.onResolve({\n' +
              '    at setup (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38640:19)\n' +
              '    at handlePlugins (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:842:23)\n' +
              '    at Object.buildOrServe (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1136:7)\n' +
              '    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:2064:17\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.build (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:2063:14)\n' +
              '    at Object.build (/home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/esbuild/lib/main.js:1913:51)\n' +
              '    at /home/kaspar/.nvm/versions/node/v16.13.2/lib/node_modules/hathora/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38416:54\n' +
              '    at Array.map (<anonymous>)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 23,
            file: '../../client/prototype-ui/State.tsx',
            length: 16,
            line: 7,
            lineText: 'import CardPlugin from "./plugins/Card";',
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-scan" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-scan',
      text: 'Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/tmp/tussie-mussie/client/prototype-ui/plugins/Card". The package may have incorrect main/module/exports specified in its package.json.'
    }
  ],
  warnings: []
}
```

</details>

I'm guessing it was written for an older version of Hathora but there's no way to find out which. 

One solution could be a top-level package.json and you always do `npm run hathora` (or maybe global `hathora` does that for you).
```json
{
  "dependencies": {
    "hathora": "^0.5.19"
  },
  "scripts": {
    "hathora": "hathora"
  }
}
```

A less appealing but simpler solution would be to embed a version in `hathora.yml` and simply fail if hathora doesn't match.

**Comment by hpx7** [comment]
Thanks for filing. The actual issue is that the prototype UI tries to import the [Card plugin](https://github.com/hpx7/tussie-mussie/blob/develop/client/prototype-ui/plugins/Card/index.tsx) via `import CardPlugin from "./plugins/Card";`. This works if you define the plugin in an `index.ts` file but not `index.tsx`. I need to figure out how to get `tsx` plugins working with Hathora (let me know if you have any ideas).

Embedding the Hathora version in your project via a root level package.json is a totally valid option. This is something you can do already btw -- do a `npm install hathora` at root and then you can run hathora via e.g. `npx hathora dev`. I should probably document this pattern.

The only downside is for people who don't want a package.json in their root (this is for a future where there is expanded language support for Hathora, so you might have a Rust backend with a Kotlin frontend, and there is actually no Typescript in your project other than the generated prototype UI).

Let me know your thoughts on this.

**Comment by kasbah** [comment]
As the examples grow there should be way to specify the hathora version at the very least (and bonus points if it can npm install the right version needed and run it). I gave some ideas above but am not a person that cares about having a Rust / Kotlin etc. support so I will leave it up to you. 

(The issue of what's actually happening with tussie-mussie is an aside of course, let's figure that out somewhere else.)

**Comment by hpx7** [comment]
Try out the local Hathora install and let me know how you like that. I think that’s the common pattern for pinning versions of node clis

**Comment by hpx7** [comment]
I would be happy to add it to the docs as a recommended pattern/option if it works well for folks

**Comment by francislavoie** [comment]
FWIW I agree with the approach of `npm install hathora` -> `npx hathora dev`, I think it should be the default recommendation in the docs. This approach makes it better for reliable collaboration with other devs when the version is locked.
