### ISSUE TITLE
Can't build examples: "Unable to compile TypeScript"

### ISSUE THREAD

**Issue by wolf81** [hpx7/rtag#218]
I clones the project & installed npm. I also installed hathora using rpm.

Afterwards I navigate to the Pong (and Uno) directories and try to run `hathora dev`. 

During the build an error occurs: `Argument of type 'string' is not assignable to parameter of type 'Context'`

The specific error I get when trying to build Uno & Pong is as follows:

```
/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
wrapper.ts(20,35): error TS2345: Argument of type 'string' is not assignable to parameter of type 'Context'.

    at createTSError (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/index.ts:1322:43)
    at transformSource (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/esm.ts:380:37)
    at load (/usr/local/lib/node_modules/hathora/node_modules/ts-node/src/esm.ts:280:51)
    at async ESMLoader.load (node:internal/modules/esm/loader:407:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:11) {
  diagnosticCodes: [ 2345 ]
}
```

**Comment by hpx7** [comment]
There were some breaking changes on develop that were incompatible with the previously released version.

I've released 0.7.1, if you upgrade (`npm install -g hathora`) you should find that the examples work now.
